import { VacancyesDataType } from "../../../../types/vacancys";

export const VacancyMockData: VacancyesDataType = {
  totalPages: 10,
  data: [
    {
      id: "1",
      title: "UNIX Администратор",
      salaryRange: "145 000 — 200 000",
      postedDate: "07.04.2024 15:13",
      location: "Москва",
      contractType: "ДКРП",
      description: "23—35 лет, стаж от 1 года, высшее образование",
      isStarred: true,
    },
    {
      id: "2",
      title: "Менеджер по продукту",
      salaryRange: "145 000 — 200 000",
      postedDate: "02.04.2024 16:11",
      location: "Москва",
      description: "опыт работы в IT от 2 лет, знание английского языка",
      contractType: "ДКРП",
    },
    {
      id: "3",
      title: "Разработчик Java",
      salaryRange: "170 000 — 230 000",
      postedDate: "03.04.2024 12:00",
      location: "Санкт-Петербург",
      description: "23—35 лет, стаж от 1 года, высшее образование",
      contractType: "ДКРП",
    },
    {
      id: "4",
      title: "Ведущий разработчик C++",
      salaryRange: "190 000 — 260 000",
      postedDate: "04.04.2024 19:22",
      location: "Новосибирск",
      contractType: "ДКРП",
      description: "13—35 лет, стаж от 1 года, высшее образование",
      isStarred: true,
    },
    {
      id: "5",
      title: "Системный аналитик",
      salaryRange: "150 000 — 210 000",
      postedDate: "05.04.2024 22:38",
      location: "Казань",
      description: "23—35 лет, стаж от 1 года, высшее образование",
      contractType: "ДКРП",
    },
    {
      id: "6",
      title: "Frontend Developer",
      salaryRange: "160 000 — 220 000",
      postedDate: "06.04.2024 11:11",
      location: "Москва",
      description: "опыт работы в IT от 2 лет, знание английского языка",
      contractType: "ДКРП",
    },
    {
      id: "7",
      title: "Backend Developer",
      salaryRange: "165 000 — 225 000",
      postedDate: "07.04.2024 12:44",
      location: "Москва",
      description: "Ж, опыт работы в IT от 2 лет, знание английского языка",
      contractType: "ДКРП",
    },
    {
      id: "8",
      title: "DevOps Инженер",
      salaryRange: "180 000 — 240 000",
      postedDate: "29.03.2024 10:00",
      location: "Екатеринбург",
      description: "М, опыт работы в IT от 2 лет, знание английского языка",
      contractType: "ДКРП",
    },
    {
      id: "9",
      title: "Project Manager",
      salaryRange: "200 000 — 300 000",
      postedDate: "25.03.2024 13:31",
      location: "Москва",
      description: "опыт работы в IT от 2 лет, знание английского языка",
      contractType: "ДКРП",
    },
    {
      id: "10",
      title: "Тестировщик ПО",
      salaryRange: "140 000 — 190 000",
      postedDate: "21.03.2024 18:00",
      location: "Москва",
      contractType: "ДКРП",
      description: "опыт работы в IT от 2 лет, знание английского языка",
      isStarred: true,
    },
  ],
};
